=== Kizumii225/xml_coban/buoi3/1/1.2/thuvien.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="thuvien">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sach" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ten" type="xs:string"/>
              <xs:element name="tacgia" type="xs:string"/>
              <xs:element name="nam" type="xs:date"/>
              <xs:element name="theloai" type="xs:string"/>
            </xs:sequence>
            
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Kizumii225/xml_coban/buoi3/1/1.2/thuvien.xml
<?xml version="1.0" ?>
<thuvien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="thuvien.xsd">
    <sach id="S01">
        <ten>XML Cơ Bản</ten>
        <tacgia>Võ Kiều My</tacgia>
        <nam>2025</nam>
        <theloai>Công Nghệ</theloai>
    </sach>
    <sach id="S02">
        <ten>XML Cơ Bản 2</ten>
        <tacgia>Bui Huu Nhat</tacgia>
        <nam>2025</nam>
        <theloai>Công Nghệ</theloai>
    </sach>
    <sach id="S03">
        <ten>XML Cơ Bản 3</ten>
        <tacgia>Lê Văn Mộng</tacgia>
        <nam>2025</nam>
        <theloai>Công Nghệ</theloai>
    </sach>
</thuvien>
